name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: install dependencies
        run: sudo apt-get install -y libboost-dev nlohmann-json3-dev
      - uses: actions/checkout@v4
      - uses: education/autograding@v1